const SET_LISTS = 'SET_LISTS';
const ADD_LIST = 'ADD_LIST';
const EDIT_LIST = 'EDIT_LIST';
const REMOVE_LIST = 'REMOVE_LIST';

const OPEN_DELETE_LIST_MODAL = 'OPEN_DELETE_LIST_MODAL';
const OPEN_EDIT_LIST_MODAL = 'OPEN_EDIT_LIST_MODAL';
const OPEN_EDIT_ITEM_MODAL = 'OPEN_EDIT_ITEM_MODAL';
const OPEN_DELETE_GROUP_MODAL = 'OPEN_DELETE_GROUP_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';

const SET_CURRENT_LIST = 'SET_CURRENT_LIST';
const SET_ITEMS = 'SET_ITEMS';
const ADD_ITEM = 'ADD_ITEM';
const EDIT_ITEM = 'EDIT_ITEM';
const REMOVE_ITEM = 'REMOVE_ITEM';

const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
const SET_SEARCH_FIELD_VALUE = 'SET_SEARCH_FIELD_VALUE';
const SET_SEARCH_MENU_VISIBILITY = 'SET_SEARCH_MENU_VISIBILITY';
const CHANGE_FOCUS = 'CHANGE_FOCUS';

const SET_GROUPS = 'SET_GROUPS';
const ADD_GROUP = 'ADD_GROUP';
const UPDATE_GROUP = 'UPDATE_GROUP';
const DELETE_GROUP = 'DELETE_GROUP';
const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';

const GET = 'GET';
const POST = 'POST';
const PUT = 'PUT';
const DELETE = 'DELETE';

const API_CALL = 'API_CALL';
const API_START = 'API_START';
const API_STOP = 'API_STOP';
const API_LOADING = 'API_LOADING';
const SET_API_ERROR = 'SET_API_ERROR';
const REMOVE_API_ERROR = 'REMOVE_API_ERROR';
const SET_API_SUCCESS = 'SET_API_SUCCESS';
const REMOVE_API_SUCCESS = 'REMOVE_API_SUCCESS';

const ROUTER_LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

export {
  SET_LISTS, ADD_LIST, EDIT_LIST, REMOVE_LIST,
  OPEN_DELETE_LIST_MODAL, OPEN_EDIT_LIST_MODAL,
  OPEN_EDIT_ITEM_MODAL, OPEN_DELETE_GROUP_MODAL, CLOSE_MODAL,
  SET_CURRENT_LIST,
  SET_ITEMS, ADD_ITEM, EDIT_ITEM, REMOVE_ITEM, SET_SEARCH_RESULTS,
  SET_SEARCH_FIELD_VALUE,
  SET_SEARCH_MENU_VISIBILITY, CHANGE_FOCUS,
  SET_GROUPS, ADD_GROUP, UPDATE_GROUP, DELETE_GROUP, SET_CURRENT_GROUP,
  GET, POST, PUT, DELETE, API_CALL, API_START,
  API_STOP, API_LOADING, SET_API_ERROR, REMOVE_API_ERROR, SET_API_SUCCESS, REMOVE_API_SUCCESS,
  ROUTER_LOCATION_CHANGE,
};
