const SET_LISTS = 'SET_LISTS';
const ADD_LIST = 'ADD_LIST';
const REMOVE_LIST = 'REMOVE_LIST';

const OPEN_LISTS_MODAL = 'OPEN_LISTS_MODAL';
const OPEN_EDIT_ITEM_MODAL = 'OPEN_EDIT_ITEM_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';

const SET_CURRENT_LIST = 'SET_CURRENT_LIST';
const SET_ITEMS = 'SET_ITEMS';
const ADD_ITEM = 'ADD_ITEM';
const EDIT_ITEM = 'EDIT_ITEM';
const REMOVE_ITEM = 'REMOVE_ITEM';
const TOGGLE_ITEM = 'TOGGLE_ITEM';

const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
const SET_SEARCH_FIELD_VALUE = 'SET_SEARCH_FIELD_VALUE';
const SET_SEARCH_MENU_VISIBILITY = 'SET_SEARCH_MENU_VISIBILITY';
const CHANGE_FOCUS = 'CHANGE_FOCUS';

const SET_GROUPS = 'SET_GROUPS';

const GET = 'GET';
const POST = 'POST';
const PUT = 'PUT';
const DELETE = 'DELETE';

const API_CALL = 'API_CALL';
const API_START = 'API_START';
const API_STOP = 'API_STOP';
const API_LOADING = 'API_LOADING';
const SET_API_ERROR = 'SET_API_ERROR';
const REMOVE_API_ERROR = 'REMOVE_API_ERROR';

export {
  SET_LISTS, ADD_LIST, REMOVE_LIST, OPEN_LISTS_MODAL, OPEN_EDIT_ITEM_MODAL, CLOSE_MODAL,
  SET_CURRENT_LIST,
  SET_ITEMS, ADD_ITEM, EDIT_ITEM, REMOVE_ITEM, TOGGLE_ITEM, SET_SEARCH_RESULTS,
  SET_SEARCH_FIELD_VALUE,
  SET_SEARCH_MENU_VISIBILITY, CHANGE_FOCUS,
  SET_GROUPS,
  GET, POST, PUT, DELETE, API_CALL, API_START,
  API_STOP, API_LOADING, SET_API_ERROR, REMOVE_API_ERROR,
};
